file_path: "../SRP073391/reads/paired-reads"
fastq_screen:
  conf: "fastq_screen.conf"
  threads: 5

params:
  fastq_screen: '' 
  multiqc: --fullnames --title "QC fastq screen and fastqc" 
           --comment "Quality control, Fastqc plus Fastq Screen to check for contamination from common sources"
